[package]
name = "amareleo-chain-resources"
version = "2.0.1"
authors = ["The Amareleo Team <support@windeveloper.com>"]
homepage = "https://amareleo.com"
repository = "https://github.com/kaxxa123/amareleo-chain"
license = "Apache-2.0"
edition = "2021"

[dependencies]
